## Redirect requests on /api to out API server
[[redirects]]
  from = "/media/*"
  to = "https://f000.backblazeb2.com/file/herreshaus/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
